import js from '@eslint/js';
import typescript from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import prettier from 'eslint-config-prettier';

export default [
  js.configs.recommended,
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        browser: true,
        es2021: true,
        node: true,
        console: true,
        process: true,
        self: true,
        caches: true,
        Headers: true,
        URL: true,
        Response: true,
        fetch: true,
        navigator: true,
        window: true,
        document: true,
        localStorage: true,
        sessionStorage: true,
        location: true,
        history: true,
        MouseEvent: true,
        KeyboardEvent: true,
        Event: true,
        CustomEvent: true,
        FormData: true,
        Blob: true,
        File: true,
        FileReader: true,
        HTMLInputElement: true,
        HTMLDivElement: true,
        HTMLFormElement: true,
        HTMLImageElement: true,
        HTMLElement: true,
        IntersectionObserver: true,
        ResizeObserver: true,
        EventListener: true,
        TouchEvent: true,
        URLSearchParams: true,
        HeadersInit: true,
        AbortSignal: true,
        WebSocket: true,
        Worker: true,
        ServiceWorker: true,
        Notification: true,
        PushManager: true,
        PushSubscription: true,
        describe: true,
        it: true,
        test: true,
        expect: true,
        beforeEach: true,
        afterEach: true,
        beforeAll: true,
        afterAll: true,
        jest: true,
        setTimeout: true,
        clearTimeout: true,
        setInterval: true,
        clearInterval: true,
        require: true,
        global: true,
        NodeJS: true,
        React: true,
        alert: true,
        globalThis: true,
        Request: true,
        RequestInit: true,
        AbortController: true,
        performance: true,
        NotificationOptions: true,
        ServiceWorkerRegistration: true,
        IDBDatabase: true,
        indexedDB: true,
        IDBOpenDBRequest: true,
        isDevelopment: true,
        crypto: true,
        ResizeObserver: true,
        TextEncoder: true,
        Console: true,
        TimerHandler: true,
        FrameRequestCallback: true,
        Storage: true,
        Navigator: true,
        Document: true,
        RequestInfo: true,
        btoa: true,
        atob: true,
      },
    },
    plugins: {
      '@typescript-eslint': typescript,
      react,
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      // Security rules
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-script-url': 'error',
      'no-void': 'error',
      
      // React security
      'react/no-danger': 'error',
      'react/no-unsafe': 'error',
      
      // Accessibility
      'jsx-a11y/anchor-is-valid': 'warn',
      'jsx-a11y/alt-text': 'warn',
      
      // TypeScript rules
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': 'error',
    },
  },
  prettier,
];