import js from '@eslint/js';
import typescript from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import prettier from 'eslint-config-prettier';

export default [
  js.configs.recommended,
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    ignores: ['**/*.test.{js,jsx,ts,tsx}', '**/__tests__/**', '**/__mocks__/**'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        browser: true,
        es2021: true,
        node: true,
        console: true,
        document: true,
        window: true,
        navigator: true,
        localStorage: true,
        sessionStorage: true,
        setTimeout: true,
        clearTimeout: true,
        setInterval: true,
        clearInterval: true,
        fetch: true,
        URL: true,
        Blob: true,
        File: true,
        FormData: true,
        WebSocket: true,
        Event: true,
        CustomEvent: true,
        DOMException: true,
        HTMLInputElement: true,
        HTMLDivElement: true,
        HTMLButtonElement: true,
        HTMLAnchorElement: true,
        HTMLImageElement: true,
        HTMLCanvasElement: true,
        HTMLVideoElement: true,
        HTMLAudioElement: true,
        HTMLElement: true,
        Element: true,
        Node: true,
        NodeList: true,
        HTMLCollection: true,
        requestAnimationFrame: true,
        cancelAnimationFrame: true,
        alert: true,
        confirm: true,
        prompt: true,
        atob: true,
        btoa: true,
        TextEncoder: true,
        TextDecoder: true,
        crypto: true,
        indexedDB: true,
        IDBFactory: true,
        IDBDatabase: true,
        IDBTransaction: true,
        IDBObjectStore: true,
        IDBRequest: true,
        IDBCursor: true,
        IDBKeyRange: true,
        IDBVersionChangeEvent: true,
        serviceWorker: true,
        location: true,
        history: true,
        screen: true,
        performance: true,
        IntersectionObserver: true,
        ResizeObserver: true,
        MutationObserver: true,
        Promise: true,
        Map: true,
        Set: true,
        WeakMap: true,
        WeakSet: true,
        Proxy: true,
        Reflect: true,
        Symbol: true,
        JSON: true,
        Math: true,
        Date: true,
        RegExp: true,
        String: true,
        Number: true,
        Boolean: true,
        Array: true,
        Object: true,
        Function: true,
        Error: true,
        TypeError: true,
        ReferenceError: true,
        SyntaxError: true,
        EvalError: true,
        RangeError: true,
        URIError: true,
        parseInt: true,
        parseFloat: true,
        isNaN: true,
        isFinite: true,
        encodeURIComponent: true,
        decodeURIComponent: true,
        encodeURI: true,
        decodeURI: true,
        escape: true,
        unescape: true,
        global: true,
        process: true,
        Buffer: true,
        __dirname: true,
        __filename: true,
        module: true,
        exports: true,
        require: true,
        globalThis: true,
        self: true,
        Worker: true,
        SharedWorker: true,
        MessageChannel: true,
        MessagePort: true,
        BroadcastChannel: true,
        StorageEvent: true,
        UIEvent: true,
        MouseEvent: true,
        KeyboardEvent: true,
        TouchEvent: true,
        FocusEvent: true,
        WheelEvent: true,
        DragEvent: true,
        ClipboardEvent: true,
        CompositionEvent: true,
        AnimationEvent: true,
        TransitionEvent: true,
        ProgressEvent: true,
        PageTransitionEvent: true,
        PopStateEvent: true,
        HashChangeEvent: true,
        BeforeUnloadEvent: true,
        UnloadEvent: true,
        LoadEvent: true,
        DOMContentLoadedEvent: true,
        ReadyStateChangeEvent: true,
        ErrorEvent: true,
        PromiseRejectionEvent: true,
        SecurityPolicyViolationEvent: true,
        ReportingObserver: true,
        PerformanceObserver: true,
        UserTiming: true,
        NavigationTiming: true,
        ResourceTiming: true,
        PaintTiming: true,
        LongTask: true,
        FrameTiming: true,
        FirstInputTiming: true,
        LargestContentfulPaint: true,
        LayoutShift: true,
        CumulativeLayoutShift: true,
        FirstContentfulPaint: true,
        TimeToFirstByte: true,
        SearchParams: true,
        URLSearchParams: true,
        Path2D: true,
        CanvasGradient: true,
        CanvasPattern: true,
        CanvasRenderingContext2D: true,
        WebGLRenderingContext: true,
        WebGL2RenderingContext: true,
        OffscreenCanvas: true,
        OffscreenCanvasRenderingContext2D: true,
        ImageBitmap: true,
        ImageBitmapRenderingContext: true,
        WebGLBuffer: true,
        WebGLFramebuffer: true,
        WebGLProgram: true,
        WebGLQuery: true,
        WebGLRenderbuffer: true,
        WebGLSampler: true,
        WebGLShader: true,
        WebGLSync: true,
        WebGLTexture: true,
        WebGLTransformFeedback: true,
        WebGLUniformLocation: true,
        WebGLVertexArrayObject: true,
        GPU: true,
        GPUAdapter: true,
        GPUSupportedFeatures: true,
        GPUSupportedLimits: true,
        GPUDevice: true,
        GPUQueue: true,
        GPUCommandBuffer: true,
        GPURenderPassEncoder: true,
        GPUComputePassEncoder: true,
        GPURenderBundleEncoder: true,
        GPUQuerySet: true,
        GPUBuffer: true,
        GPUTexture: true,
        GPUTextureView: true,
        GPUSampler: true,
        GPUShaderModule: true,
        GPUPipelineLayout: true,
        GPURenderPipeline: true,
        GPUComputePipeline: true,
        GPUCommandEncoder: true,
        GPURenderBundle: true,
        GPUExternalTexture: true,
        XR: true,
        XRSystem: true,
        XRSession: true,
        XRRenderState: true,
        XRFrame: true,
        XRSpace: true,
        XRView: true,
        XRViewerPose: true,
        XRLayer: true,
        XRWebGLLayer: true,
        XRCubeLayer: true,
        XRCylinderLayer: true,
        XREquirectLayer: true,
        XRPlane: true,
        XRPlaneSet: true,
        XRAnchor: true,
        XRAnchorSet: true,
        XRHitTestResult: true,
        XRHitTestSource: true,
        XRRay: true,
        XRTransientInputHitTestResult: true,
        XRTransientInputHitTestSource: true,
        XRInputSource: true,
        XRInputSourceArray: true,
        XRInputSourceEvent: true,
        XRInputSourcesChangeEvent: true,
        XRReferenceSpace: true,
        XRReferenceSpaceEvent: true,
        XRHand: true,
        XRJointSpace: true,
        XRInputPose: true,
        XRWebGLBinding: true,
        XRMediaBinding: true,
        XRDepthInformation: true,
        XRCPUDepthInformation: true,
        XRWebGLDepthInformation: true,
        XRHitTestInformation: true,
        XRAnchorInformation: true,
        XRPlaneInformation: true,
        XRImageTrackingResult: true,
        XRMesh: true,
        XRMeshSet: true,
        describe: true,
        test: true,
        it: true,
        expect: true,
        beforeEach: true,
        afterEach: true,
        beforeAll: true,
        afterAll: true,
        jest: true,
      },
    },
    plugins: {
      '@typescript-eslint': typescript,
      react,
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['error', { 'argsIgnorePattern': '^_' }],
      'no-unused-vars': ['error', { 'argsIgnorePattern': '^_' }],
      'jsx-a11y/click-events-have-key-events': 'warn',
      'jsx-a11y/no-static-element-interactions': 'warn',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
  {
    files: ['**/*.test.{js,jsx,ts,tsx}', '**/__tests__/**', '**/__mocks__/**'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        browser: true,
        es2021: true,
        node: true,
        console: 'readonly',
        process: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        location: 'readonly',
        history: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        WebSocket: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        TouchEvent: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLFormElement: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        jest: 'readonly',
        vi: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': typescript,
      react,
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['error', { 'argsIgnorePattern': '^_' }],
      'no-unused-vars': ['error', { 'argsIgnorePattern': '^_' }],
      'jsx-a11y/click-events-have-key-events': 'warn',
      'jsx-a11y/no-static-element-interactions': 'warn',
      'no-undef': 'off',
      '@typescript-eslint/no-undef': 'off',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
  {
    ignores: ['dist/', 'node_modules/', 'build/', '*.config.*'],
  },
  prettier,
];