/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'hsl(var(--color-primary-50) / <alpha-value>)',
          100: 'hsl(var(--color-primary-100) / <alpha-value>)',
          200: 'hsl(var(--color-primary-200) / <alpha-value>)',
          300: 'hsl(var(--color-primary-300) / <alpha-value>)',
          400: 'hsl(var(--color-primary-400) / <alpha-value>)',
          500: 'hsl(var(--color-primary-500) / <alpha-value>)',
          600: 'hsl(var(--color-primary-600) / <alpha-value>)',
          700: 'hsl(var(--color-primary-700) / <alpha-value>)',
          800: 'hsl(var(--color-primary-800) / <alpha-value>)',
          900: 'hsl(var(--color-primary-900) / <alpha-value>)',
          DEFAULT: 'hsl(var(--color-primary) / <alpha-value>)',
        },
        neutral: {
          50: 'hsl(var(--color-neutral-50) / <alpha-value>)',
          100: 'hsl(var(--color-neutral-100) / <alpha-value>)',
          200: 'hsl(var(--color-neutral-200) / <alpha-value>)',
          300: 'hsl(var(--color-neutral-300) / <alpha-value>)',
          400: 'hsl(var(--color-neutral-400) / <alpha-value>)',
          500: 'hsl(var(--color-neutral-500) / <alpha-value>)',
          600: 'hsl(var(--color-neutral-600) / <alpha-value>)',
          700: 'hsl(var(--color-neutral-700) / <alpha-value>)',
          800: 'hsl(var(--color-neutral-800) / <alpha-value>)',
          900: 'hsl(var(--color-neutral-900) / <alpha-value>)',
          950: 'hsl(var(--color-neutral-950) / <alpha-value>)',
          DEFAULT: 'hsl(var(--color-neutral) / <alpha-value>)',
        },
        indigo: {
          50: 'hsl(var(--color-indigo-50) / <alpha-value>)',
          100: 'hsl(var(--color-indigo-100) / <alpha-value>)',
          200: 'hsl(var(--color-indigo-200) / <alpha-value>)',
          300: 'hsl(var(--color-indigo-300) / <alpha-value>)',
          400: 'hsl(var(--color-indigo-400) / <alpha-value>)',
          500: 'hsl(var(--color-indigo-500) / <alpha-value>)',
          600: 'hsl(var(--color-indigo-600) / <alpha-value>)',
          700: 'hsl(var(--color-indigo-700) / <alpha-value>)',
          800: 'hsl(var(--color-indigo-800) / <alpha-value>)',
          900: 'hsl(var(--color-indigo-900) / <alpha-value>)',
          DEFAULT: 'hsl(var(--color-indigo) / <alpha-value>)',
        },
        blue: {
          50: 'hsl(var(--color-blue-50) / <alpha-value>)',
          100: 'hsl(var(--color-blue-100) / <alpha-value>)',
          200: 'hsl(var(--color-blue-200) / <alpha-value>)',
          300: 'hsl(var(--color-blue-300) / <alpha-value>)',
          400: 'hsl(var(--color-blue-400) / <alpha-value>)',
          500: 'hsl(var(--color-blue-500) / <alpha-value>)',
          600: 'hsl(var(--color-blue-600) / <alpha-value>)',
          700: 'hsl(var(--color-blue-700) / <alpha-value>)',
          800: 'hsl(var(--color-blue-800) / <alpha-value>)',
          900: 'hsl(var(--color-blue-900) / <alpha-value>)',
          DEFAULT: 'hsl(var(--color-blue) / <alpha-value>)',
        },
        orange: {
          50: 'hsl(var(--color-orange-50) / <alpha-value>)',
          100: 'hsl(var(--color-orange-100) / <alpha-value>)',
          200: 'hsl(var(--color-orange-200) / <alpha-value>)',
          300: 'hsl(var(--color-orange-300) / <alpha-value>)',
          400: 'hsl(var(--color-orange-400) / <alpha-value>)',
          500: 'hsl(var(--color-orange-500) / <alpha-value>)',
          600: 'hsl(var(--color-orange-600) / <alpha-value>)',
          700: 'hsl(var(--color-orange-700) / <alpha-value>)',
          800: 'hsl(var(--color-orange-800) / <alpha-value>)',
          900: 'hsl(var(--color-orange-900) / <alpha-value>)',
          DEFAULT: 'hsl(var(--color-orange) / <alpha-value>)',
        },
        red: {
          50: 'hsl(var(--color-red-50) / <alpha-value>)',
          100: 'hsl(var(--color-red-100) / <alpha-value>)',
          200: 'hsl(var(--color-red-200) / <alpha-value>)',
          300: 'hsl(var(--color-red-300) / <alpha-value>)',
          400: 'hsl(var(--color-red-400) / <alpha-value>)',
          500: 'hsl(var(--color-red-500) / <alpha-value>)',
          600: 'hsl(var(--color-red-600) / <alpha-value>)',
          700: 'hsl(var(--color-red-700) / <alpha-value>)',
          800: 'hsl(var(--color-red-800) / <alpha-value>)',
          900: 'hsl(var(--color-red-900) / <alpha-value>)',
          DEFAULT: 'hsl(var(--color-red) / <alpha-value>)',
        },
        green: {
          50: 'hsl(var(--color-green-50) / <alpha-value>)',
          100: 'hsl(var(--color-green-100) / <alpha-value>)',
          200: 'hsl(var(--color-green-200) / <alpha-value>)',
          300: 'hsl(var(--color-green-300) / <alpha-value>)',
          400: 'hsl(var(--color-green-400) / <alpha-value>)',
          500: 'hsl(var(--color-green-500) / <alpha-value>)',
          600: 'hsl(var(--color-green-600) / <alpha-value>)',
          700: 'hsl(var(--color-green-700) / <alpha-value>)',
          800: 'hsl(var(--color-green-800) / <alpha-value>)',
          900: 'hsl(var(--color-green-900) / <alpha-value>)',
          DEFAULT: 'hsl(var(--color-green) / <alpha-value>)',
        },
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
      },
      borderRadius: {
        'card': '1rem',
        'card-lg': '1.5rem',
        'pill': '9999px',
      },
      boxShadow: {
        'card': '0 1px 3px 0 rgb(0 0 0 / 0.05), 0 1px 2px -1px rgb(0 0 0 / 0.05)',
        'card-hover': '0 10px 15px -3px rgb(0 0 0 / 0.08), 0 4px 6px -4px rgb(0 0 0 / 0.08)',
        'float': '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
        'subtle': '0 2px 4px 0 rgb(0 0 0 / 0.02)',
        'focus': '0 0 0 3px rgba(22, 163, 74, 0.3)',
        'focus-ring': '0 0 0 3px rgb(59 130 246 / 0.3)',
        'focus-visible': '0 0 0 3px rgba(22, 163, 74, 0.4), 0 0 0 1px rgb(255 255 255)',
      },
      fontFamily: {
        sans: ['system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'fade-in-up': 'fadeInUp 0.4s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'wave': 'wave 1.5s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        wave: {
          '0%, 100%': { opacity: '1', transform: 'translateX(0)' },
          '50%': { opacity: '0.5', transform: 'translateX(20px)' },
        },
      },
    },
  },
  plugins: [],
}
