/// <reference types="dom" />

declare global {
  interface Window {
    announceNavigation?: (message: string) => void;
  }
  
  var console: Console;
  var setTimeout: (handler: TimerHandler, timeout?: number, ...arguments: any[]) => number;
  var clearTimeout: (id?: number) => void;
  var setInterval: (handler: TimerHandler, timeout?: number, ...arguments: any[]) => number;
  var clearInterval: (id?: number) => void;
  var requestAnimationFrame: (callback: FrameRequestCallback) => number;
  var cancelAnimationFrame: (id: number) => void;
  var localStorage: Storage;
  var sessionStorage: Storage;
  var navigator: Navigator;
  var document: Document;
  var window: Window;
  var alert: (message?: any) => void;
  var confirm: (message?: string) => boolean;
  var prompt: (message?: string, _default?: string) => string | null;
  var fetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
  var btoa: (data: string) => string;
  var atob: (data: string) => string;
  var Blob: typeof Blob;
  var File: typeof File;
  var FileReader: typeof FileReader;
  var FormData: typeof FormData;
  var URLSearchParams: typeof URLSearchParams;
  var URL: typeof URL;
  var Event: typeof Event;
  var CustomEvent: typeof CustomEvent;
  var EventTarget: typeof EventTarget;
  var HTMLElement: typeof HTMLElement;
  var HTMLInputElement: typeof HTMLInputElement;
  var HTMLFormElement: typeof HTMLFormElement;
  var HTMLDivElement: typeof HTMLDivElement;
  var HTMLImageElement: typeof HTMLImageElement;
  var IntersectionObserver: typeof IntersectionObserver;
  var MutationObserver: typeof MutationObserver;
  var ResizeObserver: typeof ResizeObserver;
  var WebSocket: typeof WebSocket;
  var Worker: typeof Worker;
  var SharedWorker: typeof SharedWorker;
  var ServiceWorker: typeof ServiceWorker;
  var Notification: typeof Notification;
  var Geolocation: typeof Geolocation;
  var GeolocationPosition: typeof GeolocationPosition;
  var GeolocationPositionError: typeof GeolocationPositionError;
  var MediaDevices: typeof MediaDevices;
  var MediaStream: typeof MediaStream;
  var MediaStreamTrack: typeof MediaStreamTrack;
  var RTCPeerConnection: typeof RTCPeerConnection;
  var RTCDataChannel: typeof RTCDataChannel;
  var RTCIceCandidate: typeof RTCIceCandidate;
  var RTCSessionDescription: typeof RTCSessionDescription;
  var Performance: typeof Performance;
  var PerformanceEntry: typeof PerformanceEntry;
  var PerformanceMark: typeof PerformanceMark;
  var PerformanceMeasure: typeof PerformanceMeasure;
  var PerformanceNavigation: typeof PerformanceNavigation;
  var PerformanceResourceTiming: typeof PerformanceResourceTiming;
  var PerformanceTiming: typeof PerformanceTiming;
  var Screen: typeof Screen;
  var ScreenOrientation: typeof ScreenOrientation;
  var VisualViewport: typeof VisualViewport;
  var History: typeof History;
  var Location: typeof Location;
  var PopStateEvent: typeof PopStateEvent;
  var HashChangeEvent: typeof HashChangeEvent;
  var PageTransitionEvent: typeof PageTransitionEvent;
  var ErrorEvent: typeof ErrorEvent;
  var FocusEvent: typeof FocusEvent;
  var KeyboardEvent: typeof KeyboardEvent;
  var MouseEvent: typeof MouseEvent;
  var PointerEvent: typeof PointerEvent;
  var TouchEvent: typeof TouchEvent;
  var WheelEvent: typeof WheelEvent;
  var DragEvent: typeof DragEvent;
  var AbortSignal: typeof AbortSignal;
  var HeadersInit: typeof HeadersInit;
  var EventListener: typeof EventListener;
  var NodeJS: typeof NodeJS;
  var React: any;
  var global: any;
  var ClipboardEvent: typeof ClipboardEvent;
  var CompositionEvent: typeof CompositionEvent;
  var InputEvent: typeof InputEvent;
  var UIEvent: typeof UIEvent;
  var ProgressEvent: typeof ProgressEvent;
  var StorageEvent: typeof StorageEvent;
  var MessageEvent: typeof MessageEvent;
  var BeforeUnloadEvent: typeof BeforeUnloadEvent;
  var PageShowEvent: typeof PageShowEvent;
  var PageHideEvent: typeof PageHideEvent;
  var global: typeof globalThis;
  var NodeJS: any;
  var HeadersInit: any;
  var AbortSignal: any;
  var EventListener: any;
  var React: any;
  var TouchEvent: any;
}

export {};