export const ACCESSIBILITY_ROLES = {
  // Landmark Roles
  BANNER: 'banner',
  NAVIGATION: 'navigation',
  MAIN: 'main',
  COMPLEMENTARY: 'complementary',
  CONTENTINFO: 'contentinfo',

  // Widget Roles
  ALERT: 'alert',
  ALERTDIALOG: 'alertdialog',
  APPLICATION: 'application',
  ARTICLE: 'article',
  BUTTON: 'button',
  CELL: 'cell',
  CHECKBOX: 'checkbox',
  COLUMNHEADER: 'columnheader',
  COMBOBOX: 'combobox',
  DIALOG: 'dialog',
  DIRECTORY: 'directory',
  DOCUMENT: 'document',
  FEED: 'feed',
  FIGURE: 'figure',
  FORM: 'form',
  GRID: 'grid',
  GRIDCELL: 'gridcell',
  GROUP: 'group',
  HEADING: 'heading',
  IMG: 'img',
  LINK: 'link',
  LIST: 'list',
  LISTBOX: 'listbox',
  LISTITEM: 'listitem',
  LOG: 'log',
  MARQUEE: 'marquee',
  MATH: 'math',
  MENU: 'menu',
  MENUBAR: 'menubar',
  MENUITEM: 'menuitem',
  MENUITEMCHECKBOX: 'menuitemcheckbox',
  MENUITEMRADIO: 'menuitemradio',
  NONE: 'none',
  NOTE: 'note',
  OPTION: 'option',
  PRESENTATION: 'presentation',
  PROGRESSBAR: 'progressbar',
  RADIO: 'radio',
  RADIOGROUP: 'radiogroup',
  REGION: 'region',
  ROW: 'row',
  ROWGROUP: 'rowgroup',
  ROWHEADER: 'rowheader',
  SCROLLBAR: 'scrollbar',
  SEARCH: 'search',
  SEARCHBOX: 'searchbox',
  SEPARATOR: 'separator',
  SLIDER: 'slider',
  SPINBUTTON: 'spinbutton',
  STATUS: 'status',
  SWITCH: 'switch',
  TAB: 'tab',
  TABLE: 'table',
  TABLIST: 'tablist',
  TABPANEL: 'tabpanel',
  TERM: 'term',
  TEXTBOX: 'textbox',
  TIMER: 'timer',
  TOOLBAR: 'toolbar',
  TOOLTIP: 'tooltip',
  TREE: 'tree',
  TREEGRID: 'treegrid',
  TREEITEM: 'treeitem',
} as const;

export const ACCESSIBILITY_STATES = {
  BUSY: 'aria-busy',
  CHECKED: 'aria-checked',
  CURRENT: 'aria-current',
  DISABLED: 'aria-disabled',
  EXPANDED: 'aria-expanded',
  GRABBED: 'aria-grabbed',
  HIDDEN: 'aria-hidden',
  INVALID: 'aria-invalid',
  LIVE: 'aria-live',
  PRESSED: 'aria-pressed',
  READONLY: 'aria-readonly',
  REQUIRED: 'aria-required',
  SELECTED: 'aria-selected',
} as const;

export const ACCESSIBILITY_PROPERTIES = {
  ACTIVEDESCENDANT: 'aria-activedescendant',
  ATOMIC: 'aria-atomic',
  AUTOCOMPLETE: 'aria-autocomplete',
  COLCOUNT: 'aria-colcount',
  COLINDEX: 'aria-colindex',
  COLSPAN: 'aria-colspan',
  CONTROLS: 'aria-controls',
  DESCRIBEDBY: 'aria-describedby',
  DETAILS: 'aria-details',
  DISABLED: 'aria-disabled',
  DROPEFFECT: 'aria-dropeffect',
  ERRORMESSAGE: 'aria-errormessage',
  FLOWTO: 'aria-flowto',
  HASPOPUP: 'aria-haspopup',
  KEYSHORTCUTS: 'aria-keyshortcuts',
  LABEL: 'aria-label',
  LABELLEDBY: 'aria-labelledby',
  LEVEL: 'aria-level',
  LIVE: 'aria-live',
  MODAL: 'aria-modal',
  MULTILINE: 'aria-multiline',
  MULTISELECTABLE: 'aria-multiselectable',
  ORIENTATION: 'aria-orientation',
  OWNS: 'aria-owns',
  PLACEHOLDER: 'aria-placeholder',
  POSINSET: 'aria-posinset',
  READONLY: 'aria-readonly',
  RELEVANT: 'aria-relevant',
  REQUIRED: 'aria-required',
  ROLES: 'role',
  ROWCOUNT: 'aria-rowcount',
  ROWINDEX: 'aria-rowindex',
  ROWSPAN: 'aria-rowspan',
  SETSIZE: 'aria-setsize',
  SORT: 'aria-sort',
  VALUEMAX: 'aria-valuemax',
  VALUEMIN: 'aria-valuemin',
  VALUENOW: 'aria-valuenow',
  VALUETEXT: 'aria-valuetext',
} as const;

export const LIVE_REGION_POLITENESS = {
  OFF: 'off',
  POLITE: 'polite',
  ASSERTIVE: 'assertive',
} as const;

export const KEYBOARD_SHORTCUTS = {
  ESCAPE: 'Escape',
  ENTER: 'Enter',
  SPACE: ' ',
  TAB: 'Tab',
  ARROW_UP: 'ArrowUp',
  ARROW_DOWN: 'ArrowDown',
  ARROW_LEFT: 'ArrowLeft',
  ARROW_RIGHT: 'ArrowRight',
  HOME: 'Home',
  END: 'End',
  PAGE_UP: 'PageUp',
  PAGE_DOWN: 'PageDown',
  F1: 'F1',
  F2: 'F2',
  F3: 'F3',
  F4: 'F4',
  F5: 'F5',
  F6: 'F6',
  F7: 'F7',
  F8: 'F8',
  F9: 'F9',
  F10: 'F10',
  F11: 'F11',
  F12: 'F12',
} as const;

export const ARIA_LIVE_RELEVANT = {
  ADDITIONS: 'additions',
  REMOVALS: 'removals',
  TEXT: 'text',
  ALL: 'all',
} as const;

export const FOCUS_MANAGEMENT = {
  AUTOFOCUS: 'autoFocus',
  TABINDEX: 'tabIndex',
  TABINDEX_NEGATIVE: -1,
  TABINDEX_ZERO: 0,
  TABINDEX_POSITIVE_START: 1,
} as const;

export const ACCESSIBILITY_TIPS = {
  IMAGES: [
    'Always provide alt text for images',
    'Use empty alt text (alt="") for decorative images',
    'Include alt text that describes the function, not just the appearance',
  ],
  FORMS: [
    'Associate labels with form controls',
    'Use fieldset and legend for related groups of controls',
    'Provide clear instructions for form completion',
    'Use aria-required for required fields',
    'Use aria-invalid and aria-describedby for error messages',
  ],
  KEYBOARD: [
    'Ensure all interactive elements are keyboard accessible',
    'Provide visible focus indicators',
    'Use semantic HTML elements where possible',
    'Avoid trapping users in focus loops',
  ],
  COLOR: [
    'Don\'t use color as the only way to convey information',
    'Ensure sufficient contrast (minimum 4.5:1 for normal text)',
    'Provide text alternatives for color-coded information',
  ],
  DYNAMIC_CONTENT: [
    'Use aria-live regions for dynamic content updates',
    'Use polite interruptions for non-critical updates',
    'Use assertive interruptions for critical errors',
    'Announce content changes to screen readers',
  ],
  MODALS: [
    'Set aria-modal="true" on modal dialogs',
    'Trap focus within the modal',
    'Return focus to the trigger element when closing',
    'Provide an escape mechanism',
  ],
} as const;

export const WCAG_2_1_AA_LEVELS = {
  CONTRAST_NORMAL: 4.5,
  CONTRAST_LARGE: 3.0,
  TEXT_SIZE_LARGE: '18pt' as const,
  TEXT_SIZE_LARGE_BOLD: '14pt' as const,
} as const;

export const ACCESSIBILITY_TESTING = {
  AXE_CORE: 'axe-core',
  JEST_AXE: 'jest-axe',
  TESTING_LIBRARY: '@testing-library/react',
  SCREEN_READER: 'screen-reader',
  KEYBOARD_ONLY: 'keyboard-only',
  HIGH_CONTRAST: 'high-contrast',
  NO_PREFERENCES: 'no-preferences',
} as const;
